site_name: Good Practices SRE & DevSecOps
site_description: Documentation structurée autour des bonnes pratiques DevSecOps,
  SRE, CI/CD, astreinte, observabilité et infrastructure.
site_author: Siegfried Sekkai
repo_url: https://github.com/5136Siegfried/sre-good-practices
repo_name: GitHub
edit_uri: edit/main/docs/
site_url: https://5136.fr
use_directory_urls: false
theme:
  name: material
  language: fr
  features:
  - navigation.expand
  - navigation.instant
  - search.suggest
  - content.code.copy
  - search.highlight
  - search.suggest
  - search.share
  logo: https://5136.fr/assets/images/logo.png
  favicon: https://5136.fr/assets/images/favicon.png
  palette:
  - scheme: default
    primary: teal
    accent: cyan
nav:
- Accueil: index.md
- Team: team.md
- Readme: README.md
- Contribute: contribute.md
- Architecture:
  - Overview: architecture/overview.md
- Sre:
  - Postmortem: sre/postmortem.md
  - Slo-Sli-Errorbudget: sre/slo-sli-errorbudget.md
  - Oncall-Schema: sre/oncall-schema.md
  - Oncall-Checklist: sre/oncall-checklist.md
  - Incident-Lifecycle: sre/incident-lifecycle.md
  - Oncall: sre/oncall.md
  - Ci: sre/ci.md
- Observability:
  - Prometheus: observability/prometheus.md
  - Grafana: observability/grafana.md
- Infra:
  - Terraform-Modules: infra/terraform-modules.md
  - Ansible: infra/ansible.md
- Devsecops:
  - Secrets: devsecops/secrets.md
  - Security-Pipeline: devsecops/security-pipeline.md
markdown_extensions:
- admonition
- codehilite
- toc:
    permalink: true
- footnotes
- tables
- attr_list
- pymdownx.superfences
- pymdownx.mark
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.snippets
- pymdownx.highlight
- pymdownx.tabbed
- pymdownx.details
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/5136Siegfried
  generator: false
  copyright: © 2025 – Siegfried Sekkai – Tous droits réservés
extra_css:
  - assets/css/custom.css
