---
site_name: Good Practices SRE & DevSecOps
site_description: >-
  Documentation structurée autour des bonnes pratiques DevSecOps, SRE, CI/CD, astreinte, observabilité et infrastructure.
site_author: Siegfried Sekkai
repo_url: https://github.com/5136Siegfried/sre-good-practices
repo_name: GitHub
site_url: https://5136Siegfried.github.io/sre-good-practices/

theme:
  name: material
  language: fr
  features:
    - navigation.expand
    - navigation.instant
    - search.suggest
    - content.code.copy

nav:
  - Accueil: docs/index.md
  - SRE:
      - Philosophie CI: docs/sre/ci.md
      - Astreinte: docs/sre/oncall.md
      - Checklist On-call: docs/sre/oncall-checklist.md
      - Postmortem: docs/sre/postmortem.md
      - Schema d'astreinte: docs/sre/oncall-schema.md
  - DevSecOps:
      - Sécurité CI/CD: docs/devsecops/security-pipeline.md
      - Gestion des secrets: docs/devsecops/secrets.md
  - Infrastructure:
      - Terraform: docs/infra/terraform-modules.md
      - Ansible: docs/infra/ansible.md
  - Observabilité:
      - Prometheus: docs/observability/prometheus.md
      - Grafana: docs/observability/grafana.md
  - Contribuer: contribute.md
  - À propos: team.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
