---
name: ✅ Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (pour scripts ou lint)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          pip install yamllint

      - name: Lint YAML files
        run: |
          yamllint .

      - name: Lint Bash scripts
        run: |
          find . -name '*.sh' -exec shellcheck {} +

  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform/example-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform
        run: terraform init -backend=false

      - name: Format check
        run: terraform fmt -check

      - name: Validate code
        run: terraform validate

  security-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.49.1_Linux-64bit.deb

      - name: Scan with Trivy
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed .
