name: Update MkDocs Navigation

on:
  push:
    paths:
      - 'docs/**'
      - '!mkdocs.yml'

jobs:
  update-nav:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Auto-update mkdocs.yml nav
        run: python .github/scripts/mkdocs/update_mkdocs_nav.py

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add mkdocs.yml
          git commit -m "ci: auto-update nav section in mkdocs.yml" || echo "No changes"
          git push
